apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: users-deployment
        image: oscark22/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
