apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  selector:
    matchLabels:
      app: story
  replicas: 2
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: oscark22/kub-data-demo:latest
          # env:
          #   - name: STORY_FOLDER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: data-store-env
          #         key: STORY_FOLDER
          envFrom:
            - configMapRef:
                name: data-store-env
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {}
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
